name: file_system_management_example
description: Example app for file_system_management package
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_system_management:
    path: ../
  collection: ^1.19.1
  # Video player
  video_player: ^2.9.2
  chewie: ^1.9.0
  # Audio player
  just_audio: ^0.9.42
  # Open files
  open_filex: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
